# Generated by Django 4.2.5 on 2024-01-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0004_remove_author_user_author_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='phone',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
