# Generated by Django 5.0.1 on 2024-01-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0005_author_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
